@host = https://localhost:44350

GET {{host}}/api/dinners/getall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjOGNiMjQ4OS1kYTJjLTRjNzktYThkNi1lY2U0NThmZDVjYzMiLCJqdGkiOiI5MDIxNzZhYS03MTk5LTQ2YmMtODZlYi01MmUwYWIxNGRmZWQiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZXhwIjoxNzAzMzY3ODMyLCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.ACK_gw7hg_f5pJhzLe5zlEf2atL1gUjN3OZqAIN22I8